export const STYLE_TEXT = `
:root{--di-ink:#172033;--di-muted:#667085;--di-paper:#f7f8fc;--di-line:#d9dfeb;--di-cobalt:#315be8;--di-amber:#d8932b;--di-green:#2e8b72;--di-red:#c94b56;--di-white:#fff}
.di-card,.di-ledger,.di-timeline{font-family:"Segoe UI","Microsoft YaHei",sans-serif;color:var(--color-text-primary,var(--di-ink));box-sizing:border-box}
.di-card *,.di-ledger *,.di-timeline *{box-sizing:border-box}.di-preline{white-space:pre-wrap}.di-card{width:min(680px,100%);border:1px solid var(--color-border-secondary,var(--di-line));border-radius:8px;background:var(--color-bg-primary,var(--di-white));overflow:hidden;box-shadow:0 8px 28px rgba(23,32,51,.08)}
.di-card-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:13px 16px;border-bottom:1px solid var(--color-border-secondary,var(--di-line));background:var(--color-bg-secondary,var(--di-paper))}.di-eyebrow{font:600 11px/1.2 Bahnschrift,"Segoe UI",sans-serif;letter-spacing:.13em;text-transform:uppercase;color:var(--di-cobalt)}.di-title{font-size:16px;font-weight:680}.di-subtitle{margin-top:3px;font-size:12px;color:var(--color-text-secondary,var(--di-muted))}.di-card-body{padding:18px}.di-question-text{font-size:16px;line-height:1.75}.di-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.di-button{appearance:none;border:1px solid var(--color-border-secondary,var(--di-line));border-radius:6px;padding:8px 12px;background:var(--color-bg-primary,var(--di-white));color:inherit;font:600 13px/1 "Segoe UI","Microsoft YaHei",sans-serif;cursor:pointer;transition:transform .15s ease,border-color .15s ease,background .15s ease}.di-button:hover:not(:disabled){transform:translateY(-1px);border-color:var(--di-cobalt)}.di-button:focus-visible{outline:3px solid rgba(49,91,232,.25);outline-offset:2px}.di-button:disabled{opacity:.55;cursor:not-allowed}.di-button.is-primary{background:var(--di-cobalt);border-color:var(--di-cobalt);color:#fff}.di-button.is-danger{color:var(--di-red);border-color:rgba(201,75,86,.4)}
.di-phase{display:inline-flex;border:1px solid var(--color-border-secondary,var(--di-line));border-radius:999px;padding:4px 8px;font:600 11px/1 Bahnschrift,"Segoe UI",sans-serif;color:var(--color-text-secondary,var(--di-muted));white-space:nowrap}.di-phase-awaiting_answer{border-color:rgba(49,91,232,.45);color:var(--di-cobalt)}.di-phase-ready_for_explanation,.di-phase-generating_explanation{border-color:rgba(216,147,43,.5);color:var(--di-amber)}.di-phase-awaiting_next{border-color:rgba(46,139,114,.45);color:var(--di-green)}.di-phase-completed{border-color:rgba(102,112,133,.35)}
.di-score-row{display:flex;align-items:center;gap:12px}.di-score-number{font:700 26px/1 Bahnschrift,"Segoe UI",sans-serif}.di-score-rail{display:inline-grid;grid-template-columns:repeat(10,9px);gap:3px}.di-score-rail i{display:block;height:16px;border-radius:2px;background:var(--color-bg-tertiary,#e8ebf2)}.di-score-rail.is-compact{grid-template-columns:repeat(10,5px);gap:2px}.di-score-rail.is-compact i{height:10px}.di-score-rail i.is-good{background:var(--di-green)}.di-score-rail i.is-mid{background:var(--di-amber)}.di-score-rail i.is-low{background:var(--di-red)}
.di-section{margin-top:16px;padding-top:14px;border-top:1px solid var(--color-border-secondary,var(--di-line))}.di-section-label{margin-bottom:8px;font:600 11px/1 Bahnschrift,"Segoe UI",sans-serif;letter-spacing:.08em;text-transform:uppercase;color:var(--color-text-secondary,var(--di-muted))}.di-attempt{margin-top:12px;padding:12px;border-left:3px solid var(--di-cobalt);background:var(--color-bg-secondary,var(--di-paper));border-radius:0 6px 6px 0}.di-attempt-head{display:flex;justify-content:space-between;margin-bottom:7px;font-size:12px;color:var(--color-text-secondary,var(--di-muted))}
.di-state,.di-empty{padding:28px;text-align:center;color:var(--color-text-secondary,var(--di-muted))}.di-empty{display:grid;gap:6px}.di-spinner{display:inline-block;width:14px;height:14px;margin-right:8px;border:2px solid var(--di-line);border-top-color:var(--di-cobalt);border-radius:50%;animation:di-spin .8s linear infinite}.di-notice{margin:12px 0;padding:10px 12px;border-radius:6px;background:rgba(49,91,232,.08);font-size:13px}.di-notice.is-error{background:rgba(201,75,86,.1);color:var(--di-red)}
.di-tool-error{display:flex;align-items:baseline;gap:8px;width:min(680px,100%);padding:9px 12px;border-left:3px solid var(--di-red);border-radius:0 6px 6px 0;background:rgba(201,75,86,.08);color:var(--di-red);font:13px/1.5 "Segoe UI","Microsoft YaHei",sans-serif}.di-tool-error span{color:var(--color-text-secondary,var(--di-muted))}
.di-ledger{width:min(980px,100%);border:1px solid var(--color-border-secondary,var(--di-line));border-radius:8px;background:var(--color-bg-primary,var(--di-white));overflow:hidden}.di-ledger-head{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;padding:18px;border-bottom:1px solid var(--color-border-secondary,var(--di-line))}.di-ledger-title{font-size:21px;font-weight:720}.di-ledger-tools{display:flex;gap:8px;padding:12px 18px;border-bottom:1px solid var(--color-border-secondary,var(--di-line));background:var(--color-bg-secondary,var(--di-paper))}.di-input,.di-select{min-width:0;border:1px solid var(--color-border-secondary,var(--di-line));border-radius:6px;padding:8px 10px;background:var(--color-bg-primary,var(--di-white));color:inherit}.di-input{flex:1}.di-ledger-grid{display:grid;grid-template-columns:minmax(320px,1fr) minmax(330px,.95fr);min-height:360px}.di-practice-list{border-right:1px solid var(--color-border-secondary,var(--di-line));padding:8px}.di-practice-row{display:grid;grid-template-columns:44px 1fr auto;gap:12px;align-items:center;width:100%;padding:12px;border:0;border-bottom:1px solid var(--color-border-secondary,var(--di-line));background:transparent;color:inherit;text-align:left;cursor:pointer}.di-practice-row:hover,.di-practice-row.is-selected{background:rgba(49,91,232,.06)}.di-sequence{font:700 13px/1 Bahnschrift,"Segoe UI",sans-serif;color:var(--di-cobalt)}.di-row-title{font-weight:650}.di-row-meta{margin-top:4px;font-size:12px;color:var(--color-text-secondary,var(--di-muted))}.di-detail{padding:18px;max-height:620px;overflow:auto}.di-detail-question{padding:14px 0;border-bottom:1px solid var(--color-border-secondary,var(--di-line))}.di-detail-question-head{display:flex;gap:10px;align-items:flex-start}.di-detail-question-text{flex:1;line-height:1.55}.di-detail-actions{display:flex;gap:6px;margin-top:10px}.di-link{color:var(--di-cobalt);text-decoration:none}.di-confirm{margin-top:10px;padding:10px;border:1px solid rgba(201,75,86,.35);border-radius:6px}
.di-timeline{position:fixed;right:16px;top:112px;width:278px;max-height:calc(100vh - 150px);z-index:40;border:1px solid var(--color-border-secondary,var(--di-line));border-radius:8px;background:var(--color-bg-primary,var(--di-white));box-shadow:0 12px 32px rgba(23,32,51,.12);overflow:hidden}.di-timeline-head{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;border-bottom:1px solid var(--color-border-secondary,var(--di-line));background:var(--color-bg-secondary,var(--di-paper))}.di-timeline-body{padding:8px 12px;overflow:auto;max-height:calc(100vh - 205px)}.di-time-item{position:relative;padding:10px 0 10px 25px;border-left:1px solid var(--color-border-secondary,var(--di-line))}.di-time-item::before{content:"";position:absolute;left:-5px;top:15px;width:9px;height:9px;border-radius:50%;background:var(--color-bg-primary,var(--di-white));border:2px solid var(--di-line)}.di-time-item.is-current::before{border-color:var(--di-cobalt);background:var(--di-cobalt)}.di-time-q{font-size:12px;line-height:1.45;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.di-time-meta{display:flex;align-items:center;gap:7px;margin-top:6px;font-size:11px;color:var(--color-text-secondary,var(--di-muted))}
@keyframes di-spin{to{transform:rotate(360deg)}}
@media(max-width:900px){.di-timeline{display:none}.di-ledger-grid{grid-template-columns:1fr}.di-practice-list{border-right:0;border-bottom:1px solid var(--color-border-secondary,var(--di-line))}}
@media(max-width:560px){.di-ledger-head{align-items:flex-start;flex-direction:column}.di-ledger-tools{flex-wrap:wrap}.di-select{flex:1}.di-card-body{padding:15px}.di-score-rail{grid-template-columns:repeat(10,7px)}}
@media(prefers-reduced-motion:reduce){.di-button{transition:none}.di-spinner{animation-duration:1.5s}}
`

export function installStyles() {
  if (document.getElementById('dsh-interview-styles')) return
  const style = document.createElement('style')
  style.id = 'dsh-interview-styles'
  style.textContent = STYLE_TEXT
  document.head.appendChild(style)
}
