export const INTERVIEW_ACTIONS = Object.freeze({
  START_PRACTICE: 'practice.start',
  UPDATE_PRACTICE: 'practice.update',
  GET_STATUS: 'session.status',
  CONTINUE_PRACTICE: 'practice.continue',
  SELECT_PRACTICE: 'practice.select',
  REOPEN_PRACTICE: 'practice.reopen',
  REQUEST_FINISH: 'practice.request_finish',
  COMPLETE_SUMMARY: 'practice.complete_summary',
  PRESENT_QUESTION: 'question.present',
  GET_QUESTION: 'question.get',
  UPDATE_QUESTION: 'question.update',
  DELETE_QUESTION: 'question.delete',
  OPEN_QUESTION: 'question.open',
  REQUEST_NEXT: 'question.request_next',
  RETRY_QUESTION: 'question.retry',
  REVEAL_ANSWER: 'question.reveal_answer',
  SUBMIT_ANSWER: 'answer.submit',
  SAVE_EVALUATION: 'answer.save_evaluation',
  COMPLETE_REVIEW: 'review.complete',
  LIST_PRACTICES: 'library.list',
  READ_PRACTICE_CONTEXT: 'library.read_context',
  GET_PRACTICE: 'library.get',
  GET_INSIGHTS: 'library.insights',
  GET_LEETCODE_CATALOG: 'leetcode.catalog',
  SET_LEETCODE_COMPLETION: 'leetcode.set_completion',
  EXPORT_PRACTICES: 'library.export',
  DELETE_PRACTICE: 'library.delete',
})

export const INTERVIEW_ACTION_VALUES = Object.freeze(Object.values(INTERVIEW_ACTIONS))
